# Generated by Django 4.2.10 on 2024-02-06 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('160c3540-8876-4161-a677-b0b38e0c0cb0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
