# Generated by Django 4.2.10 on 2024-02-06 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7abcee1a-a429-4a4a-8e4b-27461baea7eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7abcee1a-a429-4a4a-8e4b-27461baea7eb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7abcee1a-a429-4a4a-8e4b-27461baea7eb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
